export const storeProducts = [
  {
    id: 1,
    title: "Air Force 1 '07 LV8",
    img: "img/product-1.jpeg",
    images: [
      "img/images-1/product-1.png",
      "img/images-1/product-2.png",
      "img/images-1/product-3.png",
      "img/images-1/product-4.png",
      "img/images-1/product-5.png",
      "img/images-1/product-6.png",
      "img/images-1/product-7.png",
      "img/images-1/product-8.png",
      "img/images-1/product-9.png",
      "img/images-1/product-10.png",
      "img/images-1/product-11.png",
      "img/images-1/product-12.png",
      "img/images-1/product-13.png",
      "img/images-1/product-14.png",
      "img/images-1/product-15.png",
      "img/images-1/product-16.png",
      "img/images-1/product-17.png",
      "img/images-1/product-18.png",
      "img/images-1/product-19.png",
      "img/images-1/product-20.png",
      "img/images-1/product-21.png",
      "img/images-1/product-22.png",
      "img/images-1/product-23.png",
      "img/images-1/product-24.png",
      "img/images-1/product-25.png",
      "img/images-1/product-26.png",
      "img/images-1/product-27.png",
      "img/images-1/product-28.png",
    ],
    price: 85.00,
    brand: "Nike",
    colour: "white",
    info:
      "Add some fresh style to your sneaker rotation in these men's Air Force 1 '07 LV8 kicks from Nike exclusive to Nike. In a crisp white colourway, these trainers are built with a premium leather upper for supportive wear, while perforations to the toe box bring a breathable wear. With a tonal lacing system keepin' you locked in and a padded ankle collar for comfort, these sneakers are sat on a chunky foam filled midsole for essential cushioning and a responsive ride. Featuring an encapsulated Air Unit to the heel for impact protection, they are equipped with a grippy rubber outsole for traction on the courts and streets and are finished with Nike Air branding and tonal Swoosh branding to the sidewalls.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "Old Skool",
    img: "img/product-2.jpeg",
    images: [
      "img/images-2/product-1.png",
      "img/images-2/product-2.png",
      "img/images-2/product-3.png",
      "img/images-2/product-4.png",
      "img/images-2/product-5.png",
      "img/images-2/product-6.png",
      "img/images-2/product-7.png",
      "img/images-2/product-8.png",
      "img/images-2/product-9.png",
      "img/images-2/product-10.png",
      "img/images-2/product-11.png",
      "img/images-2/product-12.png",
      "img/images-2/product-13.png",
      "img/images-2/product-14.png",
      "img/images-2/product-15.png",
      "img/images-2/product-16.png",
      "img/images-2/product-17.png",
      "img/images-2/product-18.png",
      "img/images-2/product-19.png",
      "img/images-2/product-20.png",
      "img/images-2/product-21.png",
      "img/images-2/product-22.png",
      "img/images-2/product-23.png",
      "img/images-2/product-24.png",
      "img/images-2/product-25.png",
      "img/images-2/product-26.png",
      "img/images-2/product-27.png",
      "img/images-2/product-28.png",
    ],
    price: 60.00,
    brand: "Vans",
    colour: "black",
    info:
      "A true innovator, these men's Old Skool trainers from Vans introduced the world to the iconic side stripe, the instantly recognisable signature that lets everyone know you're rocking the legendary skate company. A mainstay on the footwear scene, these classic kicks have endured decade after decade thanks to their long-lasting on-board performance and effortless comfort. A canvas upper delivers lightweight wear, while a padded ankle collar keeps the foot feeling fresh. With the classic outsole pattern to the underside for supreme grip whether you're on two feet or on four wheels, finished with the iconic Off The Wall tab to the heels.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "Chuck Taylor All Star Hi",
    img: "img/product-3.jpeg",
    images: [
      "img/images-3/product-1.png",
      "img/images-3/product-2.png",
      "img/images-3/product-3.png",
      "img/images-3/product-4.png",
      "img/images-3/product-5.png",
      "img/images-3/product-6.png",
      "img/images-3/product-7.png",
      "img/images-3/product-8.png",
      "img/images-3/product-9.png",
      "img/images-3/product-10.png",
      "img/images-3/product-11.png",
      "img/images-3/product-12.png",
      "img/images-3/product-13.png",
      "img/images-3/product-14.png",
      "img/images-3/product-15.png",
      "img/images-3/product-16.png",
      "img/images-3/product-17.png",
      "img/images-3/product-18.png",
      "img/images-3/product-19.png",
      "img/images-3/product-20.png",
      "img/images-3/product-21.png",
      "img/images-3/product-22.png",
      "img/images-3/product-23.png",
      "img/images-3/product-24.png",
      "img/images-3/product-25.png",
      "img/images-3/product-26.png",
      "img/images-3/product-27.png",
      "img/images-3/product-28.png",
    ],
    price: 55.00,
    brand: "Converse",
    colour: "black",
    info:
      "Be an Allstar all of the time with these classic men's Converse All Star Hi trainers! Crafted with a black canvas upper for a simple yet street smart worthy look, these canvas shoes were originally released back in 1917 as a basketball shoe and have been worn by some of the biggest stars on the court over the years. Featuring contrast stitching throughout, these Converse shoes will help you to take your look from sport to street. Other features include: Contrast striped vulcanised midsole, metal eyelets on the lace up, Converse branding on the tongue and heel and a rubber toe guard.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "Gazelle",
    img: "img/product-4.jpeg",
    images: [
      "img/images-4/product-1.png",
      "img/images-4/product-2.png",
      "img/images-4/product-3.png",
      "img/images-4/product-4.png",
      "img/images-4/product-5.png",
      "img/images-4/product-6.png",
      "img/images-4/product-7.png",
      "img/images-4/product-8.png",
      "img/images-4/product-9.png",
      "img/images-4/product-10.png",
      "img/images-4/product-11.png",
      "img/images-4/product-12.png",
      "img/images-4/product-13.png",
      "img/images-4/product-14.png",
      "img/images-4/product-15.png",
      "img/images-4/product-16.png",
      "img/images-4/product-17.png",
      "img/images-4/product-18.png",
      "img/images-4/product-19.png",
      "img/images-4/product-20.png",
      "img/images-4/product-21.png",
      "img/images-4/product-22.png",
      "img/images-4/product-23.png",
      "img/images-4/product-24.png",
      "img/images-4/product-25.png",
      "img/images-4/product-26.png",
      "img/images-4/product-27.png",
      "img/images-4/product-28.png",
    ],
    price: 70.00,
    brand: "Adidas",
    colour: "blue",
    info:
      "Give your retro creps a refresh with these men's Gazelle trainers from adidas Originals. In a navy colourway, these creps are made with a suede and synthetic upper to keep your feet supported and lookin' luxe. With a padded ankle collar and tonal lacing for a locked-in fit, these sneaks are sat on responsive black midsole to keep your feet cushioned and comfy. With a grippy rubber outsole for traction on the streets, these trainers are finished with serrated blue 3-Stripes and golden Gazelle wording to the sidewalls, along with the iconic Trefoil in gold to the tongue and heel.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "Continental 80",
    img: "img/product-5.jpeg",
    images: [
      "img/images-5/product-1.png",
      "img/images-5/product-2.png",
      "img/images-5/product-3.png",
      "img/images-5/product-4.png",
      "img/images-5/product-5.png",
      "img/images-5/product-6.png",
      "img/images-5/product-7.png",
      "img/images-5/product-8.png",
      "img/images-5/product-9.png",
      "img/images-5/product-10.png",
      "img/images-5/product-11.png",
      "img/images-5/product-12.png",
      "img/images-5/product-13.png",
      "img/images-5/product-14.png",
      "img/images-5/product-15.png",
      "img/images-5/product-16.png",
      "img/images-5/product-17.png",
      "img/images-5/product-18.png",
      "img/images-5/product-19.png",
      "img/images-5/product-20.png",
      "img/images-5/product-21.png",
      "img/images-5/product-22.png",
      "img/images-5/product-23.png",
      "img/images-5/product-24.png",
      "img/images-5/product-25.png",
      "img/images-5/product-26.png",
      "img/images-5/product-27.png",
      "img/images-5/product-28.png",
    ],
    price: 75.00,
    brand: "Adidas",
    colour: "white",
    info:
      "Bringing back a look from the '80s, these men's Continental 80 trainers from adidas Originals add a retro look to your 'fits. In a fresh white colourway, they're built with a premium leather upper that has a French terry lining for extra comfort and a throwback edge. In a nod to old-school tennis shoes, these sneakers are sat on a split rubber cupsole that's comfy and flexible for everyday wear. With a woven, two-tone stripe to the sidewalls in scarlet and navy, they're finished up with a vintage logo window and Trefoil branding to the tongue and heel.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Air Max 270",
    img: "img/product-6.jpeg",
    images: [
      "img/images-6/product-1.png",
      "img/images-6/product-2.png",
      "img/images-6/product-3.png",
      "img/images-6/product-4.png",
      "img/images-6/product-5.png",
      "img/images-6/product-6.png",
      "img/images-6/product-7.png",
      "img/images-6/product-8.png",
      "img/images-6/product-9.png",
      "img/images-6/product-10.png",
      "img/images-6/product-11.png",
      "img/images-6/product-12.png",
      "img/images-6/product-13.png",
      "img/images-6/product-14.png",
      "img/images-6/product-15.png",
      "img/images-6/product-16.png",
      "img/images-6/product-17.png",
      "img/images-6/product-18.png",
      "img/images-6/product-19.png",
      "img/images-6/product-20.png",
      "img/images-6/product-21.png",
      "img/images-6/product-22.png",
      "img/images-6/product-23.png",
      "img/images-6/product-24.png",
      "img/images-6/product-25.png",
      "img/images-6/product-26.png",
      "img/images-6/product-27.png",
      "img/images-6/product-28.png",
    ],
    price: 115.00,
    brand: "Nike",
    colour: "Brown",
    info:
      "Pump up your sneaker collection and make a statement on the streets with these men's Air Max 270 trainers from Nike. In a beige colourway with black accents, these trainers are made with a breathable textile upper to keep your feet cool, while synthetic support to the heel adds stability in every step. With a padded ankle collar and tonal lacing for a locked-in fit, these creps are sat on a foam midsole with an orange visible Air unit to the heel for responsive cushioning in every step. Coming with a grippy rubber outsole for standout traction on the streets, these trainers are finished with 270 branding to the tongue and heel, along with white Swoosh branding to the sidewalls and toe.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Stan Smith",
    img: "img/product-7.jpeg",
    images: [
      "img/images-7/product-1.png",
      "img/images-7/product-2.png",
      "img/images-7/product-3.png",
      "img/images-7/product-4.png",
      "img/images-7/product-5.png",
      "img/images-7/product-6.png",
      "img/images-7/product-7.png",
      "img/images-7/product-8.png",
      "img/images-7/product-9.png",
      "img/images-7/product-10.png",
      "img/images-7/product-11.png",
      "img/images-7/product-12.png",
      "img/images-7/product-13.png",
      "img/images-7/product-14.png",
      "img/images-7/product-15.png",
      "img/images-7/product-16.png",
      "img/images-7/product-17.png",
      "img/images-7/product-18.png",
      "img/images-7/product-19.png",
      "img/images-7/product-20.png",
      "img/images-7/product-21.png",
      "img/images-7/product-22.png",
      "img/images-7/product-23.png",
      "img/images-7/product-24.png",
      "img/images-7/product-25.png",
      "img/images-7/product-26.png",
      "img/images-7/product-27.png",
      "img/images-7/product-28.png",
    ],
    price: 75.00,
    brand: "Adidas",
    colour: "white",
    info:
      "Switch up your rotation with these men's Stan Smith Vulc trainers from adidas Originals. In a fresh white colourway with black accents, these kicks are made with a leather upper bringin' premium style and essential support. Sat on a responsive tonal midsole for next-level cushioning, these sneaks are equipped with a grippy rubber outsole for traction. With perforated 3-Stripes and Stan Smith branding to the sidewalls, these creps are finished with Trefoil branding to the tongue and heel.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
  }
];

export const detailProduct = {
    id: 1,
    title: "Air Force 1 '07 LV8",
    img: "img/product-1.jpeg",
    images: [
      "img/images-1/product-1.png",
      "img/images-1/product-2.png",
      "img/images-1/product-3.png",
      "img/images-1/product-4.png",
      "img/images-1/product-5.png",
      "img/images-1/product-6.png",
      "img/images-1/product-7.png",
      "img/images-1/product-8.png",
      "img/images-1/product-9.png",
      "img/images-1/product-10.png",
      "img/images-1/product-11.png",
      "img/images-1/product-12.png",
      "img/images-1/product-13.png",
      "img/images-1/product-14.png",
      "img/images-1/product-15.png",
      "img/images-1/product-16.png",
      "img/images-1/product-17.png",
      "img/images-1/product-18.png",
      "img/images-1/product-19.png",
      "img/images-1/product-20.png",
      "img/images-1/product-21.png",
      "img/images-1/product-22.png",
      "img/images-1/product-23.png",
      "img/images-1/product-24.png",
      "img/images-1/product-25.png",
      "img/images-1/product-26.png",
      "img/images-1/product-27.png",
      "img/images-1/product-28.png",
    ],
    price: 85.00,
    brand: "Nike",
    colour: "white",
    info:
      "Add some fresh style to your sneaker rotation in these men's Air Force 1 '07 LV8 kicks from Nike exclusive to Nike. In a crisp white colourway, these trainers are built with a premium leather upper for supportive wear, while perforations to the toe box bring a breathable wear. With a tonal lacing system keepin' you locked in and a padded ankle collar for comfort, these sneakers are sat on a chunky foam filled midsole for essential cushioning and a responsive ride. Featuring an encapsulated Air Unit to the heel for impact protection, they are equipped with a grippy rubber outsole for traction on the courts and streets and are finished with Nike Air branding and tonal Swoosh branding to the sidewalls.",
    inCart: false,
    inStock: true,
    count: 0,
    total: 0
};
